### PR TITLE
Fix Endpoint.choices() by assigning http_session (to fix #198)

### LINKED ISSUE #198: Endpoint.choices() does not work in 4.1.0
`http_session` is not set in `.choices()` in version 4.1.0:

```
>>> netbox.dcim.devices.choices()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.7/dist-packages/pynetbox/core/endpoint.py", line 327, in choices
    ssl_verify=self.api.ssl_verify,
  File "/usr/local/lib/python3.7/dist-packages/pynetbox/core/query.py", line 367, in options
    return self._make_call(verb="options")
  File "/usr/local/lib/python3.7/dist-packages/pynetbox/core/query.py", line 243, in _make_call
    req = getattr(self.http_session, verb)(
AttributeError: 'NoneType' object has no attribute 'options'
>>>

```

### PR DESCRIPTION
**Pull request by markkuleinio**
Fixes #198

### CODE REVIEW

**Comment by markkuleinio** [comment]
Actually, why do we allow `http_session` default to `None` in `Request.__init__()`, when in `Request._make_call()` (which is used with every verb) there is:

```
        req = getattr(self.http_session, verb)(
            url_override or self.url, headers=headers, verify=self.ssl_verify,
            params=params, json=data
        )
```
--> if `http_session` is `None`, then an exception will be evident.

So actually `http_session` should **not** be an optional argument for `Request`.

**Comment by markkuleinio** [comment]
I made also `base` a required argument in `Request.__init__()` because of
```
self.base = self.normalize_url(base)
```
(which will raise an exception if `base` is `None` or empty string). I would assume that if a `Request` object is instantiated then we do have an URL that we are dealing with... 😃
