### ISSUE TITLE
pynetbox 3.4.11 to 4.0.4 incompatibility

### ISSUE THREAD

**Issue by craig** [digitalocean/pynetbox#130]
This code works fine with python 3.5.6 and pynetbox 3.4.11, but not with 4.0.4.

```
#!/usr/bin/env python
import pynetbox
import os
netboxtoken=os.environ["NETBOXTOKEN"]
netboxurl=os.environ["NETBOXURL"]
nb = pynetbox.api(netboxurl, token=netboxtoken)

devices = nb.dcim.devices.all()
for device in devices:
        try:
                ip=device.primary_ip4.address.ip
                print (ip,device)
        except:
                pass
```

device.primary_ip4.address.ip seems broken? Or has there been an API change? I looked at the readme and couldn't find anything.

Error from python: 'str' object has no attribute 'ip'

**Comment by zachmoody** [comment]
Yeah, this is part of what necessitated a major version bump. It's the result of dropping netaddr which we used use to turn any IP or prefix field in NetBox's response into `netaddr.IPNetwork` objects. We're leaving that to the end-user now if they need it.
