### ISSUE TITLE
Endpoint.choices() does not work in 4.1.0

### ISSUE THREAD

**Issue by markkuleinio** [digitalocean/pynetbox#198]
`http_session` is not set in `.choices()` in version 4.1.0:

```
>>> netbox.dcim.devices.choices()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.7/dist-packages/pynetbox/core/endpoint.py", line 327, in choices
    ssl_verify=self.api.ssl_verify,
  File "/usr/local/lib/python3.7/dist-packages/pynetbox/core/query.py", line 367, in options
    return self._make_call(verb="options")
  File "/usr/local/lib/python3.7/dist-packages/pynetbox/core/query.py", line 243, in _make_call
    req = getattr(self.http_session, verb)(
AttributeError: 'NoneType' object has no attribute 'options'
>>>

```
